# Generated by Django 3.2.6 on 2023-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230113_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.AddField(
            model_name='review',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
