# Generated by Django 3.2.6 on 2023-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230113_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='descr',
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
