# Generated by Django 3.2.6 on 2023-01-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230113_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
